all: constructor controller readInput install start rule getFunction wired legalAddr cumulate vecdot vecdis updateTCAM begTransmission endTransmission modifyCap

constructor:
	g++ -c constructor.cpp

controller:
	g++ -c controller.cpp

readInput:
	g++ -c readInput.cpp

install:
	g++ -c install.cpp

start:
	g++ -c start.cpp

rule:
	g++ -c rule.cpp

getFunction:
	g++ -c getFunction.cpp

wired:
	g++ -c wired.cpp

legalAddr:
	g++ -c legalAddr.cpp

cumulate:
	g++ -c cumulate.cpp

vecdot:
	g++ -c vecdot.cpp

vecdis:
	g++ -c vecdis.cpp

updateTCAM:
	g++ -c updateTCAM.cpp

begTransmission:
	g++ -c begTransmission.cpp

endTransmission:
	g++ -c endTransmission.cpp

modifyCap:
	g++ -c modifyCap.cpp
